### ISSUE TITLE
Localize the whole eLIBRARY.RU thing into English

### ISSUE THREAD

**Issue by pussiatoday** [p1m-ortho/xs-sebzer#4]
I mean the tool and the repo.

A pretty reasonable expectation was that the target audience would be overwhelmingly Russian-speaking, considering the fact [eLIBRARY.RU](https://elibrary.ru) is exclusively Russian.

Though this literature database’s not _meant_ to be exclusively Russian though, so it could still be useful for somebody to have the translation at hand. In the setting of SR conduct, possibly.

Could even consider translating the whole website UI through the same script for instance.

And will surely need more publicity on that in this case.

**Comment by rodionstepanov** [comment]
no need, Google translate hepls

**Comment by pussiatoday** [comment]
> no need, Google translate hepls

It is actually a mystery how good it became with translation of Russian to English. It has just become completely clear to me when I tried translating a couple [Lurkmore](https://lurkmore.to) articles this way. You can check it out too if you want:

* [Ne nuzhen — Lurkmore (Google Translation)](https://translate.google.com/translate?sl=ru&tl=en&u=http%3A%2F%2Flurkmore.to%2FНе_нужен)
* [ChSV — Lurkmore (Google Translation)](https://translate.google.com/translate?sl=ru&tl=en&u=http%3A%2F%2Flurkmore.to%2FЧСВ)
* [Bydlo — Lurkmore (Google Translation)](https://translate.google.com/translate?sl=ru&tl=en&u=http%3A%2F%2Flurkmore.to%2FБыдло)

Works like a charm! Seeing that Lurk is hard slang deep into culture, the translation outcomes are really amazing.

Effectively, the opposite (Google Translate being good at English-Russian translation) is also true, judging from how well our folk enjoys reading scientific literature in English with hardly any English-speaking skills.
