### ISSUE TITLE
Не работает экспорт по выдаче из оглавления номера

### ISSUE THREAD

**Issue by rodionstepanov** [p1m-ortho/xs-sebzer#8]
На странице типа https://elibrary.ru/contents.asp?id=33590137, получается пустой bib-файл.

**Comment by pussiatoday** [comment]
Да, не работает.

@rodionstepanov, огромное спасибо за фидбек! Это очень ценные находки, когда выдает пустые файлы; сколько уже их поправил.

Отдебажу.

**Comment by rodionstepanov** [comment]
Это вам спасибо. Скрипт просто бомба. Столько времени экономит.
Если экспорт с страницы такого рода будет работать, то автомат решится проблема как экспортировать с индивидуальной страницы статьи.

**Comment by pussiatoday** [comment]
Некоторые задачи, такие как формирование подборки систематического обзора (у нас есть опыт обработки тысяч записей), вручную выполнять вообще нереально.

**Comment by rodionstepanov** [comment]
На этой странице скрипт (вер. 0.1.7) блокирует "Добавить выделенные статьи в подборку:".
Отключаю - работает.

**Comment by pussiatoday** [comment]
О, это скрипт блокирует? У меня тоже не работает, но я думал, что какая-то внешняя причина.

Действительно работает при отключении скрипта.

Сейчас буду разбираться.
